"""Adding Admin-Tag(Boolean) to user

Revision ID: 12cd0ca0ef47
Revises: 64a4184f7d6a
Create Date: 2023-03-14 12:30:12.783891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cd0ca0ef47'
down_revision = '64a4184f7d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_tag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin_tag')

    # ### end Alembic commands ###
